### ISSUE TITLE
Can we get comparison histogram from 'plot_comparison' ?

### ISSUE THREAD

**Issue by XiaoDong-SHI** [cyrraz/plothist#142]
Hi experts,

I'd like to get the comparison histogram when I use  'plot_comparison'?  
@0ctagon told me I can use the values and uncertainties from 'get_comparison' to make a new histogram. It works, of course. 
But could we directly get the histogram? It's already [there](https://github.com/cyrraz/plothist/blob/main/src/plothist/plotters.py#L582) in 'plot_comparison' fucntion.
I noticed we can get axis returned from 'plot_comparison', but I failed to get the histogram from the axis. So do you think it's good idea to also return the 'hist_comparison' for the  'plot_comparison' function?

By the way, what's can we do with returning the axis? If nothing else, maybe we can just return the 'plot_comparison' function?

Cheers,
Xiaodong

**Comment by XiaoDong-SHI** [comment]
And, one minor thing to support the second question, the 'plot_comparison' needs axis as an argument always. So...

**Comment by 0ctagon** [comment]
The `return ax` in `plot_comparison` is indeed useless since it's a required argument, but I don't think it's the job of `plot_comparison` to return a histogram.
We could add an option to `get_comparison` to return the values as histograms, but we would have problems for the asymmetrical uncertainties cases, so let see what @cyrraz has to say about the strategy here.

I think we could at least add an example in the doc to create a boost-histogram from values and uncertainties

```
values, lower_uncertainty, upper_uncertainty = get_comparison(h1, h2, comparison="pull")
h_pull = h1.copy()
h_pull[:] = np.c_[values, lower_uncertainty**2] # Takes [values, variances], doesn't work directly if uncertainties are asymmetrical.
```

**Comment by cyrraz** [comment]
I agree with @0ctagon that this is not the role of `plot_comparison` to return something else than an `axis`, even if the `axis` is not used.
We do have a function that gives the comparison values and uncertainties: [get_comparison()](https://plothist.readthedocs.io/en/latest/documentation/documentation.html#plothist.comparison.get_comparison), please use that function.

The function does not return an histogram, because:
1. as @0ctagon mentions, boost-histogram histograms do not support asymmetric uncertainties;
2. the returned histogram you would get would not be a counting histogram, so the user may easily make mistakes if they are not careful. For example, let's say that you want to compare two efficiencies on a same data sample, creating "efficiency" histograms and then getting a ratio or a difference of efficiencies with the comparison functions of `plothist` would give you a wrong result, because the uncertainties are correlated in this case.

For the reason 2. above, I do no think you should use the code example written by @0ctagon unless you know exactly what you are doing, because the resulting histogram is not a counting histogram.

**Comment by XiaoDong-SHI** [comment]
Thanks for your replies and help. Yes, I respect your decision. And I guess the example given by @0ctagon would be helpful, with the warning from @cyrraz , like the 'ratio' in comparison() handles the uncorrelated two samples, e.g. data and MC for systematic uncertainties calculation.
 
For my case, yes, I tried to compare efficiencies from two different samples.

**Comment by XiaoDong-SHI** [comment]
Closed.
