### ISSUE TITLE
savefig cuts away luminosity label

### ISSUE THREAD

**Issue by miverone** [cyrraz/plothist#71]
I noticed an issue with the function `savefig` when used with `plot_mc`. The code below produces the plots `plot_mc.pdf` and `compare_data_mc.pdf`. However, for `plot_mc.pdf` the luminosity label is cut away in the pdf, while it works fine with `compare_data_mc.pdf`.

```python
from plothist.generate_dummy_data import generate_dummy_data
from plothist import make_hist
from plothist import plot_mc
from plothist import compare_data_mc
from plothist import savefig
from plothist import add_luminosity

df = generate_dummy_data()
hist = make_hist(df['variable_0'],bins=50)

fig, ax = plot_mc(
    mc_hist_list = [hist],
    xlabel='variable_0'
)

add_luminosity(ax=ax, is_data=False, preliminary=True)
savefig(fig,'plot_mc.pdf')

fig, ax, ax_comparison = compare_data_mc(
    data_hist = hist,
    mc_hist_list = [hist],
    xlabel='variable_0'
)

add_luminosity(ax=ax, is_data=False, preliminary=True)
savefig(fig,'compare_data_mc.pdf')
```

[compare_data_mc.pdf](https://github.com/cyrraz/plothist/files/13445145/compare_data_mc.pdf)
[plot_mc.pdf](https://github.com/cyrraz/plothist/files/13445146/plot_mc.pdf)

**Comment by 0ctagon** [comment]
Thank you for your feedback!

This happens because the `figsize` is not large enough to have every element display. To fix this, you have the argument `new_figsize` to increase the size of the saved figure. This will only enlarge the figsize and not the size of the subplots.

For you example, you can do:
```
savefig(fig, 'plot_mc.pdf', new_figsize=(6, 4.2)) # Increase the height of the saved fig
```

The `savefig` function is still experimental, and using `fig.savefig(path, bbox_inches="tight")` is highly recommended.
